import Head from "next/head";

export default function Seo() {
  return (
    <Head>
      <title>Cruz Handmade</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}
